config/routes.rb
Rails.application.routes.draw do
  root "statistics#index"
  get "stats", to: "statistics#index"

  resources :teachers do
    resources :degrees
    resources :klasses
    member do
      get "teachers_students"
    end
  end
  resources :students do
    member do
      get "new_classes"
      post "add_classes"
    end
  end
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :registrars
  has_many :klasses, through: :registrars
  validates :name, :average_grade, :class_of, presence: true

  validates :average_grade, numericality: { only_integer: true }

  validate :class_of_in_the_future

  scope :graduating_latest, -> { select(:name).maximum(:class_of) }
  scope :graduating_soonest, -> { select(:name).minimum(:class_of) }
  scope :average_student_grade, -> { sum(:average_grade).to_f / count }
  scope :max_average, -> { maximum("average_grade") }
  scope :min_average, -> { minimum("average_grade") }
  scope :students_in_classes, -> {
    joins(:registrars).select(:name)
  }

private

  def class_of_in_the_future
    errors.add(:class_of, "must be a date in the future") if class_of <= Date.today
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %w(show edit update destroy)

  def index
    @students = Student.all
  end

  def show
    @klasses = Student.find(params[:id]).klasses
  end

  def new
    @student = Student.new
  end

  def edit; end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to @student, notice: "Student was successfully created."
    else
      render :new
    end
  end

  def update
    if @student.update(student_params)
      redirect_to @student, notice: "Student was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to students_url, notice: "Student was successfully destroyed."
  end

  def new_classes
    @classes = Klass.all
  end

  def add_classes
    return unless params[:klass_id].present?

    registrar = Registrar.new
    student = Student.find(params[:id])
    klass = Klass.find(params[:klass_id])
    registrar.klass = klass
    registrar.student = student

    redirect_to student_url(student) if registrar.save
  end

private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :average_grade, :class_of)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<% if student.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

    <ul>
    <% student.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: student, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :average_grade %>
    <%= form.text_field :average_grade %>
  </div>

  <div class="field">
    <%= form.label :class_of %>
    <%= form.date_select :class_of %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Average grade</th>
      <th>Class of</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.average_grade %></td>
        <td><%= student.class_of %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Add Class', new_classes_student_path(student) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/new_classes.html.erb
<p>Select a Class</p>
<form method='post' action='<%= add_classes_student_path(params[:id]) %>'>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <select name='klass_id'>
    <option></option>
    <% @classes.each do |c| %>
      <option value="<%= c.id %>"><%= c.name %></option>
    <% end %>
  </select>
  <input type='submit' value="submit" />
</form>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Average grade:</strong>
  <%= @student.average_grade %>
</p>

<p>
  <strong>Class of:</strong>
  <%= @student.class_of %>
</p>

<p>Classes:</p>
<ul>
<% @klasses.each do |c| %>
  <li><%= c.name %></li>
<% end %>
</ul>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>