config/routes.rb
Rails.application.routes.draw do
  root "statistics#index"
  get "stats", to: "statistics#index"

  resources :teachers do
    resources :degrees
    resources :klasses
    member do
      get "teachers_students"
    end
  end
  resources :students do
    member do
      get "new_classes"
      post "add_classes"
    end
  end
end

app/models/degree.rb
class Degree < ApplicationRecord
  before_destroy :last_degree?
  belongs_to :teacher

  before_validation :capitilze_each_word

  validates :title, :level, :completed, presence: true

  validates :title, length: { in: 2..20 }

  validates :level, inclusion: { in: [1, 2, 3, 4],
                                 message: "%<value> is not a valid size" }

  validates :level, numericality: { only_integer: true }

  validate :completed_date_not_in_future

  def last_degree?
    throw(:abort) unless number_of_degrees > 1
  end

  def number_of_degrees
    Degree.joins(:teacher).where(teacher_id: teacher.id).count
  end

private

  def capitilze_each_word
    self.title = title.titleize
  end

  def completed_date_not_in_future
    errors.add(:completed, "must be a date in the past") if completed >= Date.today
  end
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  before_action :set_degree, only: %w(show edit update destroy)

  helper_method :degree
  helper_method :degrees
  helper_method :teacher

  def index; end

  def show; end

  def new
    @degree = Degree.new
    @teacher = Teacher.find(params[:teacher_id])
  end

  def edit; end

  def create
    @teacher = Teacher.find(params[:teacher_id])
    @degree = @teacher.degrees.new(degree_params)

    if @degree.save
      redirect_to teacher_degrees_url(teacher), notice: "Degree was successfully created."
    else
      render :new
    end
  end

  def update
    if @degree.update(degree_params)
      redirect_to teacher_degrees_url(teacher, degree), notice: "Degree was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    if @degree.destroy
      redirect_to teacher_degrees_url(teacher), notice: "Degree was successfully destroyed."
    else
      redirect_to teacher_degrees_url(teacher), notice: "You cannot delete the last degree"
    end
  end

private

  def degree
    teacher.degrees
  end

  def degrees
    Degree.all
  end

  def teacher
    Teacher.find(params[:teacher_id])
  end

  def set_degree
    @degree = Degree.find(params[:id])
    @teacher = Teacher.find(params[:teacher_id])
  end

  def degree_params
    params.require(:degree).permit(:title, :level, :completed)
  end
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/views/degrees/_form.html.erb
<% if degree.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(degree.errors.count, "error") %> prohibited this degree from being saved:</h2>

    <ul>
    <% degree.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @degree, url: [@teacher, @degree], local: true) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.date_select :completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/degrees/edit.html.erb
<h1>Editing Degree</h1>

<%= render 'form', degree: @degree %>

<%= link_to 'Show', teacher_degree_path(teacher, degree) %> |
<%= link_to 'Back', teacher_degrees_path(teacher) %>

app/views/degrees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Degrees</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Level</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% degree.each do |d| %>
      <tr>
        <td><%= d.title %></td>
        <td><%= d.level %></td>
        <td><%= d.completed %></td>
        <td><%= link_to 'Show', teacher_degree_path(teacher, d) %></td>
        <td><%= link_to 'Edit', edit_teacher_degree_path(teacher, d) %></td>
        <td><%= link_to 'Destroy', teacher_degree_path(teacher, d), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Degree', new_teacher_degree_path(teacher) %>

app/views/degrees/new.html.erb
<h1>New Degree</h1>

<%= render 'form', degree: @degree %>

app/views/degrees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @degree.title %>
</p>

<p>
  <strong>Level:</strong>
  <%= @degree.level %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @degree.completed %>
</p>

<%= link_to 'Edit', edit_teacher_degree_path(teacher, @degree) %> |
<%= link_to 'Back', teacher_degrees_path(teacher) %>