config/routes.rb
Rails.application.routes.draw do
  root "statistics#index"
  get "stats", to: "statistics#index"

  resources :teachers do
    resources :degrees
    resources :klasses
    member do
      get "teachers_students"
    end
  end
  resources :students do
    member do
      get "new_classes"
      post "add_classes"
    end
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :degrees
  has_many :klasses

  validates :name, :age, presence: true

  validates :age, numericality: { only_integer: true }

  scope :max_age, -> { maximum(:age) }
  scope :min_age, -> { minimum(:age) }

  def self.students(teacher_id)
    find_by_sql("select distinct students.name from registrars
                join students on registrars.student_id = students.id
                where klass_id in ( select id from klasses where teacher_id = #{teacher_id})")
  end

  def age_i
    age.to_i
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %w(show edit update destroy)

  def index
    @teachers = Teacher.all
  end

  def show
    @students = Teacher.students(params[:id])
    @klasses = Teacher.find(params[:id]).klasses
    @degrees = Teacher.find(params[:id]).degrees
  end

  def new
    @teacher = Teacher.new
  end

  def edit; end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      redirect_to @teacher, notice: "Teacher was successfully created."
    else
      render :new
    end
  end

  def update
    if @teacher.update(teacher_params)
      redirect_to @teacher, notice: "Teacher was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @teacher.destroy
    redirect_to teachers_url, notice: "Teacher was successfully destroyed."
  end

private

  def set_teacher
    @teacher = TeacherDecorator.new(Teacher.find(params[:id]))
  end

  def teacher_params
    params.require(:teacher).permit(:name, :age)
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.age %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Add Degree', new_teacher_degree_path(teacher.id)  %></td>
        <td><%= link_to 'Add Class', new_teacher_klass_path(teacher.id)  %></td>
        <td><%= link_to 'List Classes', teacher_klasses_path(teacher.id)  %></td>
        <td><%= link_to 'List Degrees', teacher_degrees_path(teacher.id)  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Age Type:</strong>
  <%= @teacher.age_type %>
</p>

<p>
  <strong>Age:</strong>
  <%= @teacher.age %>
</p>

<p>Students:</p>
<ul>
<% @students.each do |s| %>
  <li><%= s.name %></li>
<% end %>
</ul>

<p>Classes:</p>
<ul>
  <% @klasses.each do |s| %>
    <li><%= s.name %></li>
  <% end %>
</ul>

<p>Degrees:</p>
<ul>
  <% @degrees.each do |s| %>
    <li><%= s.title %></li>
    <li><%= s.from %></li>
    <li><%= s.completed %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/teachers_students.html.erb
<h3><%= @teacher.name %>'s Students</h3>
<ul>
  <% @students.each do |s| %>
    <li><%= s.name %></li>
  <% end %>
</ul>