config/routes.rb
Rails.application.routes.draw do
  root "statistics#index"
  get "stats", to: "statistics#index"

  resources :teachers do
    resources :degrees
    resources :klasses
    member do
      get "teachers_students"
    end
  end
  resources :students do
    member do
      get "new_classes"
      post "add_classes"
    end
  end
end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController
  # TODO: Distinguish between new class and class lookup?
  helper_method :klass, :klasses, :teacher

  def index; end

  def show; end

  def new
    @klass = Klass.new
  end

  def edit; end

  def create
    @teacher = Teacher.find(params[:teacher_id])
    @klass = @teacher.klasses.new(klass_params)
    if @klass.save
      redirect_to teacher_klasses_path(@teacher), notice: "Class was successfully created."
    else
      render :new
    end
  end

  def update
    if klass.update(klass_params)
      redirect_to teacher_klass_path(teacher), notice: "Class was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    redirect_to teacher_klasses_path(teacher_id), notice: "Class was successfully destroyed." if klass.destroy
  end

private

  def klass_id
    params[:id]
  end

  def teacher_id
    params[:teacher_id]
  end

  def teacher
    Teacher.find(teacher_id)
  end

  def klass
    Klass.find(klass_id)
  end

  def klass_params
    params.require(:klass).permit(:name, :time, :level)
  end

  def klasses
    Klass.where(teacher_id: teacher_id)
  end
end

app/helpers/klasses_helper.rb
module KlassesHelper
end

app/views/klasses/_form.html.erb
<%= form_with(model: klass, url: [teacher, klass], local: true) do |form| %>
  <% if klass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(klass.errors.count, "error") %> prohibited this klass from being saved:</h2>

      <ul>
      <% klass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/klasses/edit.html.erb
<h1>Editing Klass</h1>

<%= render 'form', klass: klass %>

<%= link_to 'Show', teacher_klass_path(teacher, klass) %> |
<%= link_to 'Back', teacher_klasses_path(teacher) %>

app/views/klasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Klasses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Time</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% klasses.each do |klass| %>
      <tr>
        <td><%= klass.name %></td>
        <td><%= klass.time %></td>
        <td><%= klass.level %></td>
        <td><%= klass.teacher.name %></td>
        <td><%= link_to "Edit", edit_teacher_klass_path(klass.teacher_id, klass.id) %></td>
        <td><%= link_to "Remove Class", teacher_klass_path(klass.teacher_id, klass.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/klasses/new.html.erb
<h1>New Class</h1>

<%= render 'form', klass: @klass %>

app/views/klasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= klass.name %>
</p>

<p>
  <strong>Time:</strong>
  <%= klass.time %>
</p>

<p>
  <strong>Level:</strong>
  <%= klass.level %>
</p>

<%= link_to 'Edit', edit_teacher_klass_path(teacher, klass) %> |
<%= link_to 'Back', teacher_klasses_path(teacher) %>